services:
  mongodb:
    image: mongo:latest
    container_name: thesis_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: your_database_name
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
